document.addEventListener("DOMContentLoaded",async()=>{
  await window.SoftPlanetCatalogService.ready();
  const params=new URLSearchParams(location.search),country=params.get("country"),city=params.get("city"),category=params.get("category"),tripParam=params.get("trip"),root=document.getElementById("catalogSection"),title=document.getElementById("pageTitle"),desc=document.getElementById("pageDescription"),eyebrow=document.getElementById("eyebrow"),back=document.getElementById("backLink");
  const link=values=>`inspiration.html?${new URLSearchParams({...values,...(tripParam?{trip:tripParam}:{})})}`,escape=value=>String(value||"").replace(/[&<>"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
  const searchHost=()=>'<div id="catalogSearchHost"></div>';
  function state(message){root.innerHTML=`<div class="soft-empty"><span class="mumu-asset" data-mumu aria-hidden="true"></span><h3>這一頁還在慢慢整理</h3><p>${message}</p><a class="primary-link" href="inspiration.html">看看其他地方 →</a></div>`}
  function mountFilter(cards,{allowCustom=false,placeholder="搜尋",customContext=null}={}){window.SoftPlanetSearch.mount(document.getElementById("catalogSearchHost"),{placeholder,onSearch:term=>{let visible=0;cards.forEach(card=>{const show=card.dataset.search.toLowerCase().includes(term.toLowerCase());card.hidden=!show;if(show)visible++});document.getElementById("searchNoResult")?.remove();if(term&&visible===0){const box=document.createElement("div");box.id="searchNoResult";box.className="soft-empty custom-result";box.innerHTML=`<span class="mumu-asset" data-mumu aria-hidden="true"></span><h3>沒有找到符合的內容</h3><p>${allowCustom?"目前沒有相符內容，可以建立專屬小卡。":"目前沒有相符內容。清除搜尋後，再看看其他內容。"}</p>${allowCustom?'<button class="primary-btn" id="openCustomForm" type="button">＋ 新增專屬小卡</button>':""}`;root.appendChild(box);if(allowCustom)document.getElementById("openCustomForm").onclick=()=>renderCustomForm(box,term,customContext)}}})}
  async function renderCustomForm(box,term,context){
    const trips=await window.SoftPlanetStore.listTrips(),matching=trips.filter(trip=>trip.country===country&&trip.city===city),areas=window.SoftPlanetServices.areas(country,city);
    const referenceRows=[1,2,3].map(index=>`<div class="reference-row"><input name="reference_name_${index}" maxlength="30" aria-label="參考連結 ${index} 名稱" placeholder="名稱，例如：官方"><input name="reference_url_${index}" type="text" inputmode="url" autocapitalize="off" spellcheck="false" aria-label="參考連結 ${index} 網址" placeholder="https://…"></div>`).join("");
    box.innerHTML=`<span class="mumu-asset" data-mumu aria-hidden="true"></span><h3>新增專屬小卡</h3><p>專屬小卡可記錄景點、交通、集合地點與臨時安排。</p><form id="customPlaceForm" class="custom-place-form"><label>加入旅行<select name="trip_id" required><option value="">請選擇旅行</option>${matching.map(trip=>`<option value="${trip.id}" ${trip.id===tripParam?"selected":""}>${escape(trip.title)}</option>`).join("")}</select></label>${matching.length?"":`<p class="field-note">目前沒有「${country}・${city}」旅行，請先建立旅行後再新增。</p>`}<label>卡片名稱<input name="custom_name" required maxlength="60" value="${escape(term)}"></label><label>類型<select name="item_type" required><option value="">請選擇</option>${["景點","餐廳","住宿","交通","購物","其他"].map(item=>`<option>${item}</option>`).join("")}</select></label><label>區域<select name="area_id" required><option value="">請從正式區域選擇</option>${areas.map(area=>`<option value="${area.id}" data-name="${area.name}">${area.name}</option>`).join("")}</select></label><label>簡短描述（選填）<textarea name="short_note" placeholder="記下預約時間、集合位置或其他重要提醒，最多 100 字。"></textarea><small class="char-count"><span id="customCount">0</span> / 100</small><span class="field-error" id="noteError"></span></label><fieldset class="reference-fields"><legend>參考連結（選填，最多三組）</legend><p class="field-note">平台不限；每一組請同時填寫名稱與安全的 HTTPS 網址。</p>${referenceRows}<span class="field-error" id="referenceError"></span></fieldset><button class="primary-btn" type="submit" ${matching.length?"":"disabled"}>建立並加入旅行</button><p class="status-message" id="customStatus"></p></form>`;
    const form=document.getElementById("customPlaceForm"),note=form.elements.short_note,counter=document.getElementById("customCount");note.oninput=()=>{const count=[...note.value].length;counter.textContent=count;counter.closest(".char-count").classList.toggle("near-limit",count>=85);document.getElementById("noteError").textContent=count>100?`超出 ${count-100} 個字元，請縮短後再儲存。`:""};
    const completeUrl=value=>{const raw=String(value||"").trim();if(!raw)return"";if(/^[a-z][a-z0-9+.-]*:/i.test(raw))return raw;return`https://${raw}`};
    [1,2,3].forEach(index=>{const field=form.elements[`reference_url_${index}`];field.onblur=()=>{if(field.value.trim())field.value=completeUrl(field.value)}});
    form.onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form)),count=[...values.short_note].length;if(count>100){document.getElementById("noteError").textContent=`超出 ${count-100} 個字元，請縮短後再儲存。`;return}const references=[1,2,3].map(index=>({name:String(values[`reference_name_${index}`]||"").trim(),url:completeUrl(values[`reference_url_${index}`])}));references.forEach((item,index)=>{form.elements[`reference_url_${index+1}`].value=item.url});const incomplete=references.some(item=>(item.name&&!item.url)||(!item.name&&item.url)),invalid=references.some(item=>item.url&&!window.SoftPlanetMaps.safe(item.url));if(incomplete||invalid){document.getElementById("referenceError").textContent=incomplete?"每組參考連結都需要同時填寫名稱與網址。":"請使用安全的 HTTPS 網址；系統不接受 javascript:、data: 或其他協定。";return}values.references=references.filter(item=>item.name&&item.url);const areaOption=form.elements.area_id.options[form.elements.area_id.selectedIndex];values.country=country;values.city=city;values.area_name=areaOption.dataset.name;const item=window.SoftPlanetCustomItems.create(values);if(values.item_type==="住宿"){location.href=`trip.html?id=${encodeURIComponent(values.trip_id)}&assistant=stay&place=${encodeURIComponent(item.id)}`;return}await window.SoftPlanetStore.addPlace(values.trip_id,item.id);location.href=`place.html?id=${encodeURIComponent(item.id)}`};
  }
  function card(item){const fields=[item.name,item.city,item.subarea,item.category,item.tags,item.summary,item.transport,item.suitable,item.facilities,item.cuisine,item.signature].filter(Boolean).join(" "),detailUrl=`place.html?id=${encodeURIComponent(item.id)}`;return `<article class="place-card ${item.custom&&!item.upgraded?"custom-place-card":""}" data-search="${escape(fields)}"><a class="place-visual tone-${item.tone}" href="${detailUrl}"><span>${item.emoji}</span>${item.demo?'<small class="demo-badge">Demo</small>':item.custom&&!item.upgraded?'<small class="demo-badge">自己新增</small>':""}</a><div class="place-card-body"><p class="eyebrow">${escape([item.subarea,item.category].filter(Boolean).join("・"))}</p><h2><a href="${detailUrl}">${escape(item.name)}</a></h2><p>${escape(item.summary)}</p><div class="card-action-bar"><a class="card-detail-link" href="${detailUrl}">查看詳情 →</a><div class="card-icon-actions"><button class="card-icon-btn" type="button" data-favorite-id="${escape(item.id)}" data-favorite-name="${escape(item.name)}" aria-label="收藏${escape(item.name)}" aria-pressed="false">♡</button><button class="card-icon-btn" type="button" data-share-url="${detailUrl}" data-share-title="${escape(item.name)}｜SoftPlanet" data-share-text="${escape(item.summary)}" aria-label="分享${escape(item.name)}">↗</button></div></div></div></article>`}
  if(!country){back.href="index.html";root.innerHTML=`${searchHost()}<div class="country-grid">${window.SoftPlanetCatalog.countries.map(item=>`<a class="catalog-card country-card" data-search="${item.name}" href="${link({country:item.name})}"><span class="catalog-icon">${item.emoji}</span><div><h2>${item.name}</h2><p>${item.note}</p></div><span>›</span></a>`).join("")}</div>`;mountFilter([...root.querySelectorAll("[data-search]")],{placeholder:"搜尋國家"});return}
  if(!city){title.textContent=`${country}，想去哪座城市？`;desc.textContent="先選一座城市，MUMU 再陪你慢慢拆成景點、住宿與美食。";eyebrow.textContent="國家 › 城市";back.href="inspiration.html";const cities=window.SoftPlanetCatalog.cities[country]||[];if(!cities.length){state("目前還沒有這個國家的城市內容。");return}root.innerHTML=`${searchHost()}<div class="city-grid">${cities.map((name,index)=>`<a class="city-card tone-${["peach","sage","aqua","sand","lavender"][index%5]}" data-search="${name}" href="${link({country,city:name})}"><span>${["🏙️","🌿","🌊","☕","🚃"][index%5]}</span><h2>${name}</h2><p>打開 ${name} 的旅行靈感</p><strong>進入城市 →</strong></a>`).join("")}</div>`;mountFilter([...root.querySelectorAll("[data-search]")],{placeholder:"搜尋城市"});return}
  if(!category){title.textContent=`${city}，慢慢走就好`;desc.textContent="從最想知道的一件事開始，不需要一次把旅行排滿。";eyebrow.textContent=`${country} › ${city}`;back.href=link({country});const time=window.SoftPlanetServices.worldTime(city),weather=window.SoftPlanetServices.weather(city);root.innerHTML=`${time||weather?`<div class="city-context">${time?`<article><span>🕰️</span><strong>${city} ${time.destination}</strong><p>你的位置 ${time.local}・${time.difference}</p></article>`:""}${weather?`<article><span>🌤️</span><strong>${weather.status} ${weather.low}–${weather.high}°</strong><p>${weather.rain}・更新 ${new Date(weather.updated_at).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})}</p></article>`:""}</div>`:""}<div class="city-welcome"><span>🐻</span><div><strong>MUMU 的城市小提醒</strong><p>${city} 的內容可以自由挑選，喜歡的地方再放進「我的旅行」。</p></div></div><div class="category-grid">${window.SoftPlanetCatalog.categories.map(item=>`<a class="catalog-card category-card" href="${link({country,city,category:item.name})}"><span class="catalog-icon">${item.icon}</span><div><h2>${item.name}</h2><p>${item.note}</p></div><span>›</span></a>`).join("")}</div>`;return}
  title.textContent=`${city}・${category}`;desc.textContent=category==="城市介紹"?`先用一分鐘認識 ${city}，再選想看的內容。`:`把喜歡的${category}留著，旅行會慢慢長出自己的樣子。`;eyebrow.textContent=`${country} › ${city} › ${category}`;back.href=link({country,city});
  if(category==="城市介紹"){root.innerHTML=`<article class="story-card"><span>🧭</span><h2>${city}，適合留一點空白的城市</h2><p>SoftPlanet 建議先抓一至兩個主要區域，每天留一段沒有安排的時間。交通與營業資訊可能變動，出發前請再向官方確認。</p><a class="primary-link" href="${link({country,city,category:"景點"})}">開始看景點 →</a></article>`;return}
  if(category==="熱門行程"){root.innerHTML=`<article class="story-card"><span>🗓️</span><h2>${city} 柔軟散步一日</h2><p>上午安排一個主要景點，午後留給街區與咖啡，傍晚再到喜歡的地方看夜景。</p><a class="primary-link" href="${link({country,city,category:"景點"})}">挑選沿途景點 →</a></article>`;return}
  if(category==="伴手禮"){const key=`softplanet-souvenirs-${country}-${city}`,defaults=["送家人的點心","留給自己的小紀念","旅伴想買的東西"];let items=JSON.parse(localStorage.getItem(key)||"null")||defaults.map((name,index)=>({id:index,name,done:false}));const render=()=>{root.innerHTML=`<div class="checklist-card"><div>${items.map(item=>`<label class="check-row ${item.done?"done":""}"><input type="checkbox" data-id="${item.id}" ${item.done?"checked":""}><span>${escape(item.name)}</span><button type="button" data-remove="${item.id}">×</button></label>`).join("")}</div><form id="souvenirForm" class="inline-form"><input name="name" maxlength="30" required placeholder="新增想買的東西"><button class="secondary-btn">新增</button></form></div>`;const save=()=>localStorage.setItem(key,JSON.stringify(items));root.querySelectorAll("[data-id]").forEach(input=>input.onchange=()=>{items.find(item=>String(item.id)===input.dataset.id).done=input.checked;save();render()});root.querySelectorAll("[data-remove]").forEach(button=>button.onclick=()=>{items=items.filter(item=>String(item.id)!==button.dataset.remove);save();render()});document.getElementById("souvenirForm").onsubmit=event=>{event.preventDefault();const name=new FormData(event.currentTarget).get("name").trim();if(name){items.push({id:Date.now(),name,done:false});save();render()}}};render();return}
  const normalizedCategory=category==="美食"?["美食","餐廳"]:[category],items=window.SoftPlanetPlaces.filter(item=>item.country===country&&item.city===city&&normalizedCategory.includes(item.category));if(!items.length){state(`${city}的${category}內容還在整理中，你可以先看看其他分類。`);return}root.innerHTML=`${searchHost()}${category==="住宿"?`<div class="area-chips">${[...new Set(items.map(item=>item.subarea).filter(Boolean))].map(area=>`<span>${area}</span>`).join("")}</div>`:""}<div class="place-grid">${items.map(card).join("")}</div>`;window.SoftPlanetCardActions.mount(root);mountFilter([...root.querySelectorAll("[data-search]")],{allowCustom:["景點","住宿","美食"].includes(category),placeholder:`搜尋${category}`,customContext:{country,city,category}});
});
