document.addEventListener("DOMContentLoaded",()=>{
  const data={
    "證件與金錢":{icon:"🪪",items:[{id:"passport",name:"護照與證件",note:"出發前確認效期與簽證需求。",products:[{name:"防潑水證件夾（Demo）",icon:"👝",url:"https://www.google.com/search?q=travel+document+holder"}]},{id:"wallet",name:"旅用錢包",note:"分開放少量現金與備用卡。",products:[{name:"輕量旅用錢包（Demo）",icon:"👛",url:"https://www.google.com/search?q=travel+wallet"}]}]},
    "衣物與鞋子":{icon:"👕",items:[{id:"layers",name:"可分層穿著的衣物",note:"依天氣預報準備，避免帶太多單一厚衣。",products:[{name:"收納袋組（Demo）",icon:"🧺",url:"https://www.google.com/search?q=packing+cubes"}]},{id:"shoes",name:"好走的鞋",note:"優先選已穿習慣、不磨腳的鞋。",products:[{name:"旅行鞋袋（Demo）",icon:"👟",url:"https://www.google.com/search?q=travel+shoe+bag"}]}]},
    "盥洗與健康":{icon:"🧴",items:[{id:"toiletry",name:"隨身盥洗用品",note:"液體容量請依航空與機場規定準備。",products:[{name:"分裝瓶組（Demo）",icon:"🧴",url:"https://www.google.com/search?q=travel+bottles"}]},{id:"medicine",name:"個人常用藥",note:"保留原包裝與醫療資訊，處方藥依目的地規定準備。",products:[{name:"小型藥品收納包（Demo）",icon:"💊",url:"https://www.google.com/search?q=travel+medicine+bag"}]}]},
    "電子用品":{icon:"🔌",items:[{id:"charger",name:"充電器與充電線",note:"確認目的地電壓與插座規格。",products:[{name:"旅行轉接插頭（Demo）",icon:"🔌",url:"https://www.google.com/search?q=universal+travel+adapter"}]},{id:"powerbank",name:"行動電源",note:"行動電源通常須隨身攜帶，容量限制依航空公司規定。",products:[{name:"輕量行動電源（Demo）",icon:"🔋",url:"https://www.google.com/search?q=travel+power+bank"}]}]}
  };
  const params=new URLSearchParams(location.search),category=params.get("category"),itemId=params.get("item"),root=document.getElementById("packingContent"),title=document.getElementById("packingTitle"),desc=document.getElementById("packingDescription"),eyebrow=document.getElementById("packingEyebrow"),back=document.getElementById("packingBack"),key="softplanet-packing-checked";let checked=new Set(JSON.parse(localStorage.getItem(key)||"[]"));
  const url=(values)=>`packing.html?${new URLSearchParams(values)}`;
  if(!category){root.innerHTML=`<div class="category-grid">${Object.entries(data).map(([name,value])=>`<a class="catalog-card" href="${url({category:name})}"><span class="catalog-icon">${value.icon}</span><div><h2>${name}</h2><p>${value.items.length} 項出發前清單</p></div><span>›</span></a>`).join("")}</div>`;return;}
  const group=data[category];if(!group){location.href="packing.html";return;}back.href="packing.html";title.textContent=category;desc.textContent="勾起來的項目會留在這台裝置，下次回來還看得到。";eyebrow.textContent="行李攻略 › 類別";
  if(!itemId){root.innerHTML=`<div class="checklist-card">${group.items.map(item=>`<div class="packing-row ${checked.has(item.id)?"done":""}"><label><input type="checkbox" data-check="${item.id}" ${checked.has(item.id)?"checked":""}><span>${item.name}</span></label><a href="${url({category,item:item.id})}">查看準備方式 ›</a></div>`).join("")}</div>`;root.querySelectorAll("[data-check]").forEach(input=>input.onchange=()=>{input.checked?checked.add(input.dataset.check):checked.delete(input.dataset.check);localStorage.setItem(key,JSON.stringify([...checked]));input.closest(".packing-row").classList.toggle("done",input.checked)});return;}
  const item=group.items.find(value=>value.id===itemId);if(!item){location.href=url({category});return;}back.href=url({category});title.textContent=item.name;desc.textContent=item.note;eyebrow.textContent=`行李攻略 › ${category} › 清單`;
  root.innerHTML=`<article class="story-card packing-detail"><span>${group.icon}</span><h2>這次需要帶嗎？</h2><label class="large-check"><input type="checkbox" id="detailCheck" ${checked.has(item.id)?"checked":""}><span>${item.name}</span></label><p>${item.note}</p></article><h2 class="subsection-title">可以參考的用品</h2><p class="demo-note">以下為流程展示商品，點擊後會前往外部搜尋頁。</p><div class="product-grid">${item.products.map(product=>`<a class="product-card" href="${product.url}" target="_blank" rel="noopener noreferrer"><span>${product.icon}</span><div><small>Demo 商品</small><h3>${product.name}</h3><strong>查看商品 ↗</strong></div></a>`).join("")}</div>`;document.getElementById("detailCheck").onchange=(event)=>{event.target.checked?checked.add(item.id):checked.delete(item.id);localStorage.setItem(key,JSON.stringify([...checked]));};
});
