document.addEventListener("DOMContentLoaded",async()=>{
  const id=new URLSearchParams(location.search).get("id"),place=window.getSoftPlanetPlace(id);
  const $=(id)=>document.getElementById(id),favorite=$("favoriteBtn"),status=$("status"),picker=$("tripPicker"),sheet=$("loginSheet");
  const showCustomBadge=place.custom&&!place.upgraded;document.title=`${place.name} - SoftPlanet`;$("placeVisual").classList.add(`tone-${place.tone}`);$("placeEmoji").textContent=place.emoji;$("demoBadge").hidden=!place.demo&&!showCustomBadge;if(showCustomBadge)$("demoBadge").textContent="自己新增";$("placeMeta").textContent=`${place.country}・${place.city}・${place.category}`;$("placeName").textContent=place.name;$("placeSummary").textContent=place.summary;$("placeDuration").textContent=place.duration;$("placeBestTime").textContent=place.bestTime;$("placeAddress").textContent=place.address;$("placeTip").textContent=place.tip;
  const mapResult=window.SoftPlanetMaps.apply($("mapView"),place);if(!mapResult.url)$("mapView").hidden=true;
  if(place.category==="住宿"){$("hotelDetails").hidden=false;$("placeSuitable").textContent=place.suitable;$("placeTransport").textContent=place.transport;$("placeSurroundings").textContent=place.surroundings;$("placeFacilities").textContent=place.facilities;const links=(place.booking_links||[]).filter(item=>window.SoftPlanetMaps.safe(item.url));if(links.length){$("bookingLinks").hidden=false;$("bookingLinks").innerHTML=links.map(item=>`<a href="${window.SoftPlanetMaps.safe(item.url)}" target="_blank" rel="noopener noreferrer">${item.name} ↗</a>`).join("")}}
  const ticketLinks=(place.ticket_links||[]).filter(item=>window.SoftPlanetMaps.safe(item.url));if(place.category==="景點"&&ticketLinks.length){$("ticketPanel").hidden=false;$("ticketLinks").innerHTML=ticketLinks.map(item=>`<a href="${window.SoftPlanetMaps.safe(item.url)}" target="_blank" rel="noopener noreferrer">${item.name} ↗</a>`).join("")}
  if(place.short_note){$("userNoteCard").hidden=false;$("userNote").textContent=place.short_note;}
  const references=Array.isArray(place.reference_links)&&place.reference_links.length?place.reference_links:[place.google_map_url&&{name:"Google Maps",url:place.google_map_url},place.naver_map_url&&{name:"Naver Map",url:place.naver_map_url}].filter(Boolean);if(place.custom&&references.length){$("referenceCard").hidden=false;$("referenceList").replaceChildren(...references.slice(0,3).map(item=>{const link=document.createElement("a"),label=document.createElement("span"),arrow=document.createElement("span");link.href=window.SoftPlanetMaps.safe(item.url)||"#";link.target="_blank";link.rel="noopener noreferrer";label.className="reference-name";label.textContent=item.name;arrow.className="reference-arrow";arrow.setAttribute("aria-hidden","true");arrow.textContent="↗";link.append(label,arrow);return link}))}
  if(place.custom&&!place.upgraded&&place.upgrade_status==="available"&&place.official_match_id){$("upgradeCard").hidden=false;$("acceptUpgrade").onclick=()=>{const upgraded=window.SoftPlanetCustomItems.upgrade(place.id);if(upgraded)location.reload()};$("dismissUpgrade").onclick=()=>{window.SoftPlanetCustomItems.dismiss(place.id);$("upgradeCard").hidden=true;status.textContent="先保留原卡，之後仍可以再決定。"}}
  favorite.dataset.favoriteId=place.id;favorite.dataset.favoriteName=place.name;$("placeShareBtn").dataset.shareUrl=`place.html?id=${encodeURIComponent(place.id)}`;$("placeShareBtn").dataset.shareTitle=`${place.name}｜SoftPlanet`;$("placeShareBtn").dataset.shareText=place.summary;window.SoftPlanetCardActions.mount(document);
  async function renderPicker(){
    try{
      const session=await window.SoftPlanetStore.session();
      if(session.mode==="signedout"){picker.innerHTML=`<button class="primary-btn" id="openLogin" type="button">登入或以訪客模式加入</button>`;$("openLogin").onclick=()=>sheet.showModal();return;}
      const trips=await window.SoftPlanetStore.listTrips();
      if(!trips.length){picker.innerHTML=`<form id="inlineTripForm" class="inline-trip-form"><label for="inlineTripName">還沒有旅行，先建立一趟</label><input id="inlineTripName" name="title" required maxlength="60" placeholder="例如：東京五日慢旅行"><button class="primary-btn" type="submit">建立並加入</button></form>`;$("inlineTripForm").onsubmit=async(event)=>{event.preventDefault();const title=new FormData(event.currentTarget).get("title").trim();if(!title)return;status.textContent="正在建立旅行…";try{const trip=await window.SoftPlanetStore.createTrip({title,country:place.country,city:place.city});await window.SoftPlanetStore.addPlace(trip.id,place.id);status.innerHTML=`已加入「${title}」。<a href="trip.html?id=${encodeURIComponent(trip.id)}">查看旅行 →</a>`;await renderPicker();}catch(error){status.textContent="暫時無法建立旅行，請稍後再試。"}};return;}
      const sortedTrips=[...trips].sort((a,b)=>a.id===place.trip_id?-1:b.id===place.trip_id?1:0);picker.innerHTML=`<label for="tripSelect">選擇旅行</label><select id="tripSelect">${sortedTrips.map(trip=>`<option value="${trip.id}">${trip.title}</option>`).join("")}</select><button class="primary-btn" id="addTripBtn" type="button">加入這趟旅行</button>`;
      $("addTripBtn").onclick=async()=>{const tripId=$("tripSelect").value;$("addTripBtn").disabled=true;status.textContent="正在放進旅行…";try{await window.SoftPlanetStore.addPlace(tripId,place.id);status.innerHTML=`已加入旅行。<a href="trip.html?id=${encodeURIComponent(tripId)}">查看我的旅行 →</a>`;}catch(error){status.textContent="暫時無法加入，請檢查網路後再試。"}$("addTripBtn").disabled=false;};
    }catch(error){picker.innerHTML=`<div class="soft-empty compact-empty"><span class="mumu-asset" data-mumu aria-hidden="true"></span><h3>旅行清單暫時連不上</h3><p>可能是網路不穩，稍後再試一次。</p><button class="secondary-btn" id="retryTrips" type="button">重新載入</button></div>`;$("retryTrips").onclick=renderPicker;}
  }
  $("guestLogin").addEventListener("click",event=>{event.preventDefault();window.SoftPlanetStore.enableGuest();sheet.close();renderPicker();status.textContent="目前是訪客模式，資料只會保存在這台裝置。"});
  $("googleLogin").addEventListener("click",async event=>{event.preventDefault();$("googleLogin").disabled=true;$("loginStatus").textContent="正在前往 Google 登入…";try{await window.SoftPlanetStore.googleSignIn(`place.html?id=${encodeURIComponent(place.id)}`)}catch(error){$("loginStatus").textContent="目前無法開啟登入，請改用訪客模式或稍後再試。";$("googleLogin").disabled=false;}});
  renderPicker();
});
