document.addEventListener("DOMContentLoaded",async()=>{
  const $=(id)=>document.getElementById(id),form=$("tripForm"),list=$("tripList"),count=$("tripCount"),status=$("statusText"),sheet=$("tripLoginSheet"),planner=$("plannerCard");let pendingDelete=null,allTrips=[];
  const dateFields=document.createElement("div");dateFields.className="form-row trip-date-fields";dateFields.innerHTML=`<div><label for="startDate">旅行開始日</label><input id="startDate" name="start_date" type="date"></div><div><label for="endDate">旅行結束日</label><input id="endDate" name="end_date" type="date"></div>`;form.insertBefore(dateFields,$("addTripBtn"));
  dateFields.querySelector("[name=end_date]").addEventListener("change",event=>{const start=dateFields.querySelector("[name=start_date]");event.target.setCustomValidity(start.value&&event.target.value<start.value?"結束日期不能早於開始日期。":"")});
  function empty(title,message,action=""){list.innerHTML=`<div class="soft-empty"><span aria-hidden="true">🐻</span><h3>${title}</h3><p>${message}</p>${action}</div>`;}
  function card(trip){const article=document.createElement("article");article.className="saved-trip-card";article.innerHTML=`<div class="trip-city-icon" aria-hidden="true">${trip.city?"🏙️":"🗺️"}</div><div class="saved-trip-content"><p class="eyebrow">${[trip.country,trip.city].filter(Boolean).join("・")||"目的地慢慢決定"}</p><h3><a href="trip.html?id=${encodeURIComponent(trip.id)}">${trip.title}</a></h3><p class="trip-created-date">${new Intl.DateTimeFormat("zh-TW",{dateStyle:"medium"}).format(new Date(trip.created_at))} 建立</p></div><button class="trip-more-btn" type="button" aria-label="移除 ${trip.title}">×</button>`;article.querySelector("button").onclick=()=>{pendingDelete=trip.id;$("deleteDialog").showModal()};return article;}
  function renderTrips(term=""){const filtered=allTrips.filter(trip=>`${trip.title} ${trip.country||""} ${trip.city||""} ${trip.created_at||""} ${trip.status||""}`.toLowerCase().includes(term.toLowerCase()));if(!filtered.length){empty(term?`沒有找到符合「${term}」的旅行`:"還沒有旅行",term?"清除搜尋後再看看其他旅行。":"建立第一趟旅行，或先去旅行靈感挑一個喜歡的地方。",term?"":`<a class="primary-link" href="inspiration.html">去找旅行靈感 →</a>`);return}list.replaceChildren(...filtered.map(card))}
  async function load(){
    const session=await window.SoftPlanetStore.session();
    if(session.mode==="signedout"){planner.hidden=true;$("sessionNotice").innerHTML=`<div class="auth-notice"><span aria-hidden="true">🐻</span><div><strong>先選一種保存方式</strong><p>登入可跨裝置保存，也可以先用訪客模式體驗。</p></div><button class="primary-btn" id="chooseSession">開始使用</button></div>`;$("chooseSession").onclick=()=>sheet.showModal();count.textContent="";empty("旅行還沒開始","選擇保存方式後，就能建立第一趟旅行。");return;}
    planner.hidden=false;$("sessionNotice").innerHTML=session.mode==="guest"?`<div class="guest-notice">訪客模式・資料只保存在這台裝置 <a href="my.html">登入同步</a></div>`:"";
    try{allTrips=await window.SoftPlanetStore.listTrips();count.textContent=`${allTrips.length} 趟`;renderTrips();}catch(error){empty("旅行暫時連不上","請確認網路後重新載入。",`<button class="secondary-btn" id="retryTrips">重新載入</button>`);$("retryTrips").onclick=load;}
  }
  form.onsubmit=async(event)=>{event.preventDefault();const values=Object.fromEntries(new FormData(form));values.title=values.title.trim();if(!values.title)return;$("addTripBtn").disabled=true;status.textContent="正在建立旅行…";try{await window.SoftPlanetStore.createTrip(values);form.reset();status.textContent="旅行建立好了，MUMU 會陪你慢慢補滿。";await load();}catch(error){status.textContent="暫時無法建立旅行，請稍後再試。"}$("addTripBtn").disabled=false;};
  $("deleteDialog").addEventListener("close",async()=>{if($("deleteDialog").returnValue!=="confirm"||!pendingDelete){pendingDelete=null;return;}try{await window.SoftPlanetStore.deleteTrip(pendingDelete);status.textContent="已移除這趟旅行。";await load();}catch(error){status.textContent="暫時無法移除，請稍後再試。"}pendingDelete=null;});
  $("tripGuestLogin").onclick=(event)=>{event.preventDefault();window.SoftPlanetStore.enableGuest();sheet.close();load()};
  $("tripGoogleLogin").onclick=async(event)=>{event.preventDefault();$("tripGoogleLogin").disabled=true;$("tripLoginStatus").textContent="正在前往 Google 登入…";try{await window.SoftPlanetStore.googleSignIn("trips.html")}catch(error){$("tripLoginStatus").textContent="目前無法開啟登入，請改用訪客模式或稍後再試。";$("tripGoogleLogin").disabled=false;}};
  window.SoftPlanetSearch.mount($("tripSearch"),{placeholder:"搜尋旅行名稱、國家、城市或日期",onSearch:renderTrips});load();
});
