document.addEventListener("DOMContentLoaded",async()=>{
  const tripId=new URLSearchParams(location.search).get("id"),$=id=>document.getElementById(id),list=$("placeList"),collection=$("tripCollection"),cover=$("tripCover"),blockSection=$("tripBlockSection"),blockGrid=$("tripBlockGrid"),sheet=$("blockSheet"),removeDialog=$("blockRemoveDialog");let currentTrip=null,pendingBlock=null,placeIds=[];
  function state(title,message,link){list.innerHTML=`<div class="soft-empty compact-empty"><span>🐻</span><h3>${title}</h3><p>${message}</p>${link?`<a class="primary-link" href="${link.href}">${link.text}</a>`:""}</div>`;}
function renderContext(trip){const time=window.SoftPlanetServices.worldTime(trip.city),weather=window.SoftPlanetServices.weather(trip.city),cards=[];if(time)cards.push(`<article><span>🕰️</span><div><small>${trip.city}現在時間</small><strong>${time.destination}</strong><p>你的位置 ${time.local}・${time.difference}</p></div></article>`);if(weather)cards.push(`<article><span>🌤️</span><div><small>${weather.city}・${weather.date}・示範資料</small><strong>${weather.status} ${weather.low}–${weather.high}°</strong><p>${weather.rain}・更新 ${new Date(weather.updated_at).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})}</p></div></article>`);$("tripContextCards").innerHTML=cards.join("")}
  function blockCard(item){const meta=window.SoftPlanetServices.blockCatalog.find(block=>block.id===item.type);return `<article class="trip-block-card" data-block-card="${item.type}"><a href="block.html?trip=${encodeURIComponent(tripId)}&type=${item.type}"><span>${meta.icon}</span><div><h3>${meta.name}</h3><p>${meta.note}</p><strong>打開積木 →</strong></div></a><button type="button" data-remove-block="${item.type}" aria-label="調整 ${meta.name}">•••</button></article>`}
  function renderBlocks(){const states=window.SoftPlanetServices.blocksForTrip(tripId),active=states.filter(item=>item.status==="active");blockGrid.innerHTML=active.length?active.map(blockCard).join(""):`<div class="soft-empty compact-empty"><span>🧩</span><h3>工作區還是空的</h3><p>加入這趟需要的功能積木，不需要的工具不會出現。</p></div>`;blockGrid.querySelectorAll("[data-remove-block]").forEach(button=>button.onclick=()=>{pendingBlock=button.dataset.removeBlock;removeDialog.showModal()});renderPicker("")}
  function renderPicker(term=""){const states=window.SoftPlanetServices.blocksForTrip(tripId);$("blockPicker").innerHTML=window.SoftPlanetServices.blockCatalog.filter(item=>`${item.name}${item.note}`.includes(term)).map(item=>{const status=states.find(state=>state.type===item.id)?.status||"none",label=status==="active"?"已加入":status==="hidden"?"重新顯示":"加入";return `<article data-search-block="${item.name} ${item.note}"><span>${item.icon}</span><div><h3>${item.name}</h3><p>${item.note}</p></div><button type="button" data-add-block="${item.id}" ${status==="active"?"disabled":""}>${label}</button></article>`}).join("")||`<div class="soft-empty compact-empty"><span>🐻</span><h3>沒有找到符合「${term}」的工具</h3><p>旅行積木只能從正式功能中選擇。</p></div>`;$("blockPicker").querySelectorAll("[data-add-block]").forEach(button=>button.onclick=()=>{window.SoftPlanetServices.setBlock(tripId,button.dataset.addBlock,"active");renderBlocks()})}
  function createPlaceItem(placeId){const place=window.getSoftPlanetPlace(placeId),article=document.createElement("article");article.className=`trip-place-item ${place.custom&&!place.upgraded?"custom-trip-item":""}`;article.dataset.search=`${place.name} ${place.city} ${place.category} ${place.summary||place.short_note||""}`;article.innerHTML=`<a class="mini-place-visual tone-${place.tone}" href="place.html?id=${encodeURIComponent(place.id)}" aria-label="查看 ${place.name}">${place.emoji}</a><div><p class="eyebrow">${place.city}・${place.category}${place.custom&&!place.upgraded?'・<span class="inline-badge">自己新增</span>':""}</p><h3><a href="place.html?id=${encodeURIComponent(place.id)}">${place.name}</a></h3><a class="card-detail-link" href="place.html?id=${encodeURIComponent(place.id)}">查看詳情 →</a></div><button class="remove-place-btn" type="button" aria-label="移除 ${place.name}">×</button>`;article.querySelector(".remove-place-btn").onclick=async()=>{await window.SoftPlanetStore.removePlace(tripId,place.id);placeIds=placeIds.filter(id=>id!==place.id);renderPlaces("")};return article}
  function renderPlaces(term=""){const filtered=placeIds.map(id=>window.getSoftPlanetPlace(id)).filter(place=>`${place.name} ${place.city} ${place.category} ${place.summary||""}`.toLowerCase().includes(term.toLowerCase()));if(!filtered.length){state(term?`沒有找到符合「${term}」的內容。`:"還沒有加入地方",term?"清除搜尋，或回到旅行靈感看看其他內容。":"回到旅行靈感，挑一個最想去的地方就好。",term?null:{href:"inspiration.html",text:"去找旅行靈感 →"});return}list.replaceChildren(...filtered.map(place=>createPlaceItem(place.id)))}
  if(!tripId){cover.innerHTML=`<div class="soft-empty"><span>🐻</span><h1>找不到這趟旅行</h1><p>旅行連結可能不完整。</p><a class="primary-link" href="trips.html">返回我的旅行 →</a></div>`;collection.hidden=true;blockSection.hidden=true;return}
  try{currentTrip=await window.SoftPlanetStore.getTrip(tripId);if(!currentTrip){cover.innerHTML=`<div class="soft-empty"><span>🐻</span><h1>這趟旅行不在這裡</h1><p>可能已被移除，或需要登入原本的帳號。</p><a class="primary-link" href="trips.html">返回我的旅行 →</a></div>`;collection.hidden=true;blockSection.hidden=true;return}document.title=`${currentTrip.title} - SoftPlanet`;$("tripTitle").textContent=currentTrip.title;$("tripDestination").textContent=[currentTrip.country,currentTrip.city].filter(Boolean).join("・")||"目的地慢慢決定";$("tripCreated").textContent=`${new Intl.DateTimeFormat("zh-TW",{dateStyle:"long"}).format(new Date(currentTrip.created_at))} 建立`;$("addPlaceLink").href=`inspiration.html?${new URLSearchParams({country:currentTrip.country||"",city:currentTrip.city||"",trip:tripId})}`;renderContext(currentTrip);placeIds=await window.SoftPlanetStore.listPlaceIds(tripId);renderPlaces("");renderBlocks();window.SoftPlanetSearch.mount($("tripItemSearch"),{placeholder:"搜尋這趟旅行的景點、住宿與自訂卡",onSearch:renderPlaces});window.SoftPlanetSearch.mount($("blockSearch"),{placeholder:"搜尋旅行積木",onSearch:renderPicker});}catch(error){state("旅行暫時連不上","請確認網路後回到旅行清單再試一次。",{href:"trips.html",text:"返回我的旅行 →"})}
  $("openBlocks").onclick=()=>sheet.showModal();removeDialog.addEventListener("close",()=>{if(!pendingBlock)return;if(removeDialog.returnValue==="hide")window.SoftPlanetServices.setBlock(tripId,pendingBlock,"hidden");if(removeDialog.returnValue==="delete")window.SoftPlanetServices.deleteBlock(tripId,pendingBlock);pendingBlock=null;renderBlocks()});
});
